### PR TITLE
fix: Stat a file failed

### PR DESCRIPTION
**Pull request by npofsi**

### CODE REVIEW

**Comment by npofsi** [comment]
When stat a file with a [ftpserverlib](https://github.com/fclairamb/ftpserverlib) based server, service will throw a error: `'stat: Storager ftp {URL: localhost:2121, User: user, WorkDir: /}, [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx]: object not exist, 550 Could not list: listing a file isn't allowed'`.

**Comment by npofsi** [comment]
It's possible to use [jlaffaye/ftp](https://github.com/jlaffaye/ftp) to send a STAT command instead of LIST.

**Comment by Xuanwo** [comment]
> It's possible to use [jlaffaye/ftp](https://github.com/jlaffaye/ftp) to send a STAT command instead of LIST.

I prefer to use `stat` instead of `list`. We can provide pairs for users to config the behavior later.

**Comment by npofsi** [comment]
> 
> 
> > It's possible to use [jlaffaye/ftp](https://github.com/jlaffaye/ftp) to send a STAT command instead of LIST.
> 
> I prefer to use `stat` instead of `list`. We can provide pairs for users to config the behavior later.

For the lib is not support `stat` natively, I can only apply `stat` command though `cmd` func in lib like the lib apply `list` command.
And there are many types and functions in its package which I can't invoke. Maybe I can write my own func to achieve it.

**Review by Xuanwo — APPROVED** [review]

**Pull request merged**
